# install.packages(c('BiocManager','data.table','digest','remotes'))
# remotes::install_github('omegahat/XMLSchema')
# remotes::install_github('cran/SSOAP')
# BiocManager::install(c("SSOAP","KEGGREST","pcaMethods","Rdisop","GO.db","matrixStats","WGCNA"))
# remotes::install_github("yufree/xMSannotator")

library(factoextra)
library(tidyr)
library(xMSannotator)
library(pheatmap)
library(readxl)
library(grid)
library(MetaCycle)
library(ggpubr)
library(ggrepel)
library(vegan)
library(limma)
library(Biobase)
library(ggrepel)


runApp("~/Desktop/Rshiny App/")
